doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/ToDo/CommonModule/Migrations'
    namespace: App\ToDo\CommonModule\Migration
    table_name: migration_versions
    column_name: 'version'
    column_length: 255
    executed_at_column_name: 'executed_at'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded

    #D:\ProgramFiles\OSPanel\domains\rad_symfony\src\ToDo\CommonModule\Migrations
    #'%kernel.project_dir%/src/Migrations'



